{"text": "2024-08-29 06:34:43 | INFO    | __main__:stash:131 | run - {'image': '20231121', 'version': '0.10.1.post2', 'role': 'EpicPlayer', 'headless': True}\n", "record": {"elapsed": {"repr": "0:00:02.251841", "seconds": 2.251841}, "exception": null, "extra": {"image": "20231121", "version": "0.10.1.post2", "role": "EpicPlayer", "headless": true}, "file": {"name": "claim.py", "path": "/home/runner/work/epic-get/epic-get/epic/src/claim.py"}, "function": "stash", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 131, "message": "run", "module": "claim", "name": "__main__", "process": {"id": 3659, "name": "MainProcess"}, "thread": {"id": 139832500345728, "name": "MainThread"}, "time": {"repr": "2024-08-29 06:34:43.339309+08:00", "timestamp": 1724884483.339309}}}
{"text": "2024-08-29 06:34:47 | WARNING    | epic_games.agent:get_order_history:467 | Failed to get order history, cookie may have expired - {}\n", "record": {"elapsed": {"repr": "0:00:06.411944", "seconds": 6.411944}, "exception": null, "extra": {}, "file": {"name": "agent.py", "path": "/home/runner/work/epic-get/epic-get/epic/src/epic_games/agent.py"}, "function": "get_order_history", "level": {"icon": "‚ö†Ô∏è", "name": "WARNING", "no": 30}, "line": 467, "message": "Failed to get order history, cookie may have expired", "module": "agent", "name": "epic_games.agent", "process": {"id": 3659, "name": "MainProcess"}, "thread": {"id": 139832500345728, "name": "MainThread"}, "time": {"repr": "2024-08-29 06:34:47.499412+08:00", "timestamp": 1724884487.499412}}}
{"text": "2024-08-29 06:34:47 | DEBUG    | __main__:create_tasks:66 | Put task - {'title': 'The Callisto Protocol', 'url': 'https://store.epicgames.com/en-US/p/the-callisto-protocol'}\n", "record": {"elapsed": {"repr": "0:00:06.847264", "seconds": 6.847264}, "exception": null, "extra": {"title": "The Callisto Protocol", "url": "https://store.epicgames.com/en-US/p/the-callisto-protocol"}, "file": {"name": "claim.py", "path": "/home/runner/work/epic-get/epic-get/epic/src/claim.py"}, "function": "create_tasks", "level": {"icon": "üêû", "name": "DEBUG", "no": 10}, "line": 66, "message": "Put task", "module": "claim", "name": "__main__", "process": {"id": 3659, "name": "MainProcess"}, "thread": {"id": 139832500345728, "name": "MainThread"}, "time": {"repr": "2024-08-29 06:34:47.934732+08:00", "timestamp": 1724884487.934732}}}
{"text": "2024-08-29 06:34:47 | DEBUG    | __main__:create_tasks:66 | Put task - {'title': 'Gigantic: Rampage Edition', 'url': 'https://store.epicgames.com/en-US/p/gigantic-rampage-edition-03f532'}\n", "record": {"elapsed": {"repr": "0:00:06.847744", "seconds": 6.847744}, "exception": null, "extra": {"title": "Gigantic: Rampage Edition", "url": "https://store.epicgames.com/en-US/p/gigantic-rampage-edition-03f532"}, "file": {"name": "claim.py", "path": "/home/runner/work/epic-get/epic-get/epic/src/claim.py"}, "function": "create_tasks", "level": {"icon": "üêû", "name": "DEBUG", "no": 10}, "line": 66, "message": "Put task", "module": "claim", "name": "__main__", "process": {"id": 3659, "name": "MainProcess"}, "thread": {"id": 139832500345728, "name": "MainThread"}, "time": {"repr": "2024-08-29 06:34:47.935212+08:00", "timestamp": 1724884487.935212}}}
{"text": "2024-08-29 06:34:52 | INFO    | epic_games.agent:claim_weekly_games:294 | claim_weekly_games - {'action': 'go to store', 'url': 'https://store.epicgames.com/en-US/p/the-callisto-protocol'}\n", "record": {"elapsed": {"repr": "0:00:11.530170", "seconds": 11.53017}, "exception": null, "extra": {"action": "go to store", "url": "https://store.epicgames.com/en-US/p/the-callisto-protocol"}, "file": {"name": "agent.py", "path": "/home/runner/work/epic-get/epic-get/epic/src/epic_games/agent.py"}, "function": "claim_weekly_games", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 294, "message": "claim_weekly_games", "module": "agent", "name": "epic_games.agent", "process": {"id": 3659, "name": "MainProcess"}, "thread": {"id": 139832500345728, "name": "MainThread"}, "time": {"repr": "2024-08-29 06:34:52.617638+08:00", "timestamp": 1724884492.617638}}}
{"text": "2024-08-29 06:35:05 | INFO    | epic_games.agent:claim_weekly_games:294 | claim_weekly_games - {'action': 'go to store', 'url': 'https://store.epicgames.com/en-US/p/gigantic-rampage-edition-03f532'}\n", "record": {"elapsed": {"repr": "0:00:24.697439", "seconds": 24.697439}, "exception": null, "extra": {"action": "go to store", "url": "https://store.epicgames.com/en-US/p/gigantic-rampage-edition-03f532"}, "file": {"name": "agent.py", "path": "/home/runner/work/epic-get/epic-get/epic/src/epic_games/agent.py"}, "function": "claim_weekly_games", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 294, "message": "claim_weekly_games", "module": "agent", "name": "epic_games.agent", "process": {"id": 3659, "name": "MainProcess"}, "thread": {"id": 139832500345728, "name": "MainThread"}, "time": {"repr": "2024-08-29 06:35:05.784907+08:00", "timestamp": 1724884505.784907}}}
{"text": "2024-08-29 06:35:36 | INFO    | epic_games.agent:claim_weekly_games:294 | claim_weekly_games - {'action': 'go to store', 'url': 'https://store.epicgames.com/en-US/p/the-callisto-protocol'}\n", "record": {"elapsed": {"repr": "0:00:55.200085", "seconds": 55.200085}, "exception": null, "extra": {"action": "go to store", "url": "https://store.epicgames.com/en-US/p/the-callisto-protocol"}, "file": {"name": "agent.py", "path": "/home/runner/work/epic-get/epic-get/epic/src/epic_games/agent.py"}, "function": "claim_weekly_games", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 294, "message": "claim_weekly_games", "module": "agent", "name": "epic_games.agent", "process": {"id": 3659, "name": "MainProcess"}, "thread": {"id": 139832500345728, "name": "MainThread"}, "time": {"repr": "2024-08-29 06:35:36.287553+08:00", "timestamp": 1724884536.287553}}}
{"text": "2024-08-29 06:36:06 | INFO    | epic_games.agent:claim_weekly_games:294 | claim_weekly_games - {'action': 'go to store', 'url': 'https://store.epicgames.com/en-US/p/the-callisto-protocol'}\n", "record": {"elapsed": {"repr": "0:01:25.702739", "seconds": 85.702739}, "exception": null, "extra": {"action": "go to store", "url": "https://store.epicgames.com/en-US/p/the-callisto-protocol"}, "file": {"name": "agent.py", "path": "/home/runner/work/epic-get/epic-get/epic/src/epic_games/agent.py"}, "function": "claim_weekly_games", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 294, "message": "claim_weekly_games", "module": "agent", "name": "epic_games.agent", "process": {"id": 3659, "name": "MainProcess"}, "thread": {"id": 139832500345728, "name": "MainThread"}, "time": {"repr": "2024-08-29 06:36:06.790207+08:00", "timestamp": 1724884566.790207}}}
{"text": "2024-08-29 06:36:36 | ERROR    | __main__:run:158 | An error has been caught in function 'run', process 'MainProcess' (3659), thread 'MainThread' (139832500345728): - {}\nTraceback (most recent call last):\n  File \"/home/runner/work/epic-get/epic-get/epic/src/claim.py\", line 162, in <module>\n    asyncio.run(run())\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/runners.py\", line 44, in run\n    return loop.run_until_complete(main)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py\", line 636, in run_until_complete\n    self.run_forever()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n    self._run_once()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n    handle._run()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/events.py\", line 80, in _run\n    self._context.run(self._callback, *self._args)\n> File \"/home/runner/work/epic-get/epic-get/epic/src/claim.py\", line 158, in run\n    await agent.stash()\n  File \"/home/runner/work/epic-get/epic-get/epic/src/claim.py\", line 151, in stash\n    await self.claim_epic_games(context)\n  File \"/home/runner/work/epic-get/epic-get/epic/src/claim.py\", line 122, in claim_epic_games\n    await epic.claim_weekly_games(page, single_promotions)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/tenacity/asyncio/__init__.py\", line 189, in async_wrapped\n    return await copy(fn, *args, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/tenacity/asyncio/__init__.py\", line 111, in __call__\n    do = await self.iter(retry_state=retry_state)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/tenacity/asyncio/__init__.py\", line 153, in iter\n    result = await action(retry_state)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/tenacity/_utils.py\", line 99, in inner\n    return call(*args, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/tenacity/__init__.py\", line 418, in exc_check\n    raise retry_exc.reraise()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/tenacity/__init__.py\", line 185, in reraise\n    raise self.last_attempt.result()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/concurrent/futures/_base.py\", line 451, in result\n    return self.__get_result()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/concurrent/futures/_base.py\", line 403, in __get_result\n    raise self._exception\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/tenacity/asyncio/__init__.py\", line 114, in __call__\n    result = await fn(*args, **kwargs)\n  File \"/home/runner/work/epic-get/epic-get/epic/src/epic_games/agent.py\", line 295, in claim_weekly_games\n    await page.goto(promotion.url, wait_until=\"load\")\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/async_api/_generated.py\", line 8805, in goto\n    await self._impl_obj.goto(\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/_impl/_page.py\", line 524, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/_impl/_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py\", line 514, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nplaywright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\nnavigating to \"https://store.epicgames.com/en-US/p/the-callisto-protocol\", waiting until \"load\"\n\n", "record": {"elapsed": {"repr": "0:01:55.842134", "seconds": 115.842134}, "exception": {"type": "TimeoutError", "value": "Page.goto: Timeout 30000ms exceeded.\nCall log:\nnavigating to \"https://store.epicgames.com/en-US/p/the-callisto-protocol\", waiting until \"load\"\n", "traceback": true}, "extra": {}, "file": {"name": "claim.py", "path": "/home/runner/work/epic-get/epic-get/epic/src/claim.py"}, "function": "run", "level": {"icon": "‚ùå", "name": "ERROR", "no": 40}, "line": 158, "message": "An error has been caught in function 'run', process 'MainProcess' (3659), thread 'MainThread' (139832500345728):", "module": "claim", "name": "__main__", "process": {"id": 3659, "name": "MainProcess"}, "thread": {"id": 139832500345728, "name": "MainThread"}, "time": {"repr": "2024-08-29 06:36:36.929602+08:00", "timestamp": 1724884596.929602}}}
